# Generated by Django 5.0.6 on 2024-05-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='utilisateur',
        ),
        migrations.AlterField(
            model_name='photo',
            name='face',
            field=models.ImageField(upload_to='images'),
        ),
    ]
