# Generated by Django 5.0.6 on 2024-05-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_remove_photo_utilisateur_alter_photo_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='face',
            field=models.URLField(),
        ),
    ]
