# Generated by Django 5.0.6 on 2024-05-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_alter_photo_face'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
